"""
State schemas for the Strategic Intelligence workflow.
Defines all state objects that flow through the LangGraph.
"""
from typing import TypedDict, Literal, Optional, Annotated
from langgraph.graph.message import add_messages


# ============================================================
# MASTER ORCHESTRATOR STATE
# ============================================================

class MasterState(TypedDict):
    """State for the Master Strategic Intelligence Manager."""

    # Messages for conversation history
    messages: Annotated[list, add_messages]

    # Phase 1 output from Competitive Analyzer
    competitive_intelligence: Optional[str]

    # Phase 1 structured data for Phase 2 (CEP-specific competitor info)
    cep_tables: Optional[str]  # Raw tables with CEP competitor data
    cep_analysis: Optional[str]  # Detailed analysis with per-CEP competitors

    # Phase 2 output from Audience-to-Creative
    creative_intelligence: Optional[str]

    # User guidance captured at checkpoint
    user_guidance: Optional[str]

    # Current phase of execution
    current_phase: Literal["idle", "phase1", "checkpoint", "phase2", "complete"]

    # User decision at checkpoint
    user_decision: Optional[Literal["proceed", "stop", "guidance"]]

    # Error tracking
    error: Optional[str]


# ============================================================
# MANAGER 1: COMPETITIVE ANALYZER STATE
# ============================================================

class Manager1State(TypedDict):
    """State for Manager 1: Competitive Analyzer workflow."""

    messages: Annotated[list, add_messages]

    # Step 1: Data from 1.1 Data Merger
    raw_data_png_url: Optional[str]
    raw_data_json: Optional[dict]

    # Step 2: Analysis from 1.2 CEP Prioritizer
    cep_analysis: Optional[str]
    cep_tables: Optional[str]

    # Step 3: Insights from 1.3 CEP Insight Analyzer
    key_insights: Optional[list[str]]

    # Step 4: Visuals from 1.4 Index Visualizer
    visualization_png_url: Optional[str]
    visualization_pdf_url: Optional[str]

    # Step 5: Slide from 1.5 CEP Slide Builder
    powerpoint_url: Optional[str]

    # Final compiled report
    final_report: Optional[str]

    # Current step in workflow
    current_step: Literal["idle", "step1", "step2", "step3", "step4", "step5", "compile", "complete"]

    # Error tracking
    error: Optional[str]


# ============================================================
# MANAGER 2: AUDIENCE-TO-CREATIVE STATE
# ============================================================

class Manager2State(TypedDict):
    """State for Manager 2: Audience-to-Creative Strategy Orchestrator."""

    messages: Annotated[list, add_messages]

    # Input from Master (competitive data passed from Phase 1)
    competitive_tables: Optional[str]
    competitive_dynamics: Optional[str]

    # Step 1: Audience CEP priorities from 2.1
    audience_segments: Optional[list[dict]]
    priority_ceps: Optional[dict]

    # Step 2: Audience attributes from 2.2
    audience_attributes: Optional[dict]

    # Step 3: Strategic table (generated by manager)
    strategic_table: Optional[str]

    # Step 4: Natural language insights (generated by manager)
    strategic_insights: Optional[str]

    # Below threshold CEPs analysis
    below_threshold_analysis: Optional[str]

    # Step 5: Slide from 2.3
    powerpoint_url: Optional[str]

    # Final compiled output
    final_output: Optional[str]

    # Current step in workflow
    current_step: Literal["idle", "step1", "step2", "step3", "step4", "step5", "compile", "complete"]

    # Error tracking
    error: Optional[str]


# ============================================================
# HELPER TYPES
# ============================================================

class CEPData(TypedDict):
    """Structure for individual CEP data."""
    cep_name: str
    brand_index: float
    avg_competitor: float
    deviation: float
    top_competitors: list[dict]
    category: Literal["white_space", "winning", "underperforming", "parity"]


class AudienceSegment(TypedDict):
    """Structure for audience segment data."""
    name: str
    type: Literal["grow", "switch", "recruit"]
    demographics: Optional[str]
    behaviors: Optional[str]
    motivations: Optional[str]
    psychographics: Optional[str]
    priority_ceps: list[str]
